name: AI Code Bot

on:
  issue_comment:
    types: [created]

jobs:
  code_update:
    if: ${{ startsWith(github.event.comment.body, '/update ') }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.BOT_GH_TOKEN }}

    steps:
    # 1️⃣ Checkout repository
    - uses: actions/checkout@v4

    # 2️⃣ Extract user instructions
    - name: Extract instructions
      id: instructions
      run: |
        body="${{ github.event.comment.body }}"
        echo "USER_INSTRUCTIONS=${body:8}" >> "$GITHUB_ENV"

    # 3️⃣ Generate code based on instructions
    - name: Generate code
      run: |
        echo "Generating code..."
        # Replace this with dynamic code generation logic
        echo "// Code generated based on user instructions" > generated_file.cs

        # Example of updating an existing file
        echo "// Updated based on user instructions" >> path/to/existing_file.cs

        # Commit changes
        git add -A
        git commit -m "Code update: ${{ env.USER_INSTRUCTIONS }}"

    # 4️⃣ Push branch and create pull request
    - name: Push branch & create pull request
      run: |
        git push -u origin HEAD
        gh pr create \
          --title "Automated Update: ${{ env.USER_INSTRUCTIONS }}" \
          --body  "Changes requested via issue comment: ${{ github.event.comment.html_url }}" \
          --head  automated-update \
          --base  main