name: AI Code Bot Automation

on:
  issue_comment:
    types: [created]

jobs:
  process_request:
    if: ${{ startsWith(github.event.comment.body, '/request') }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.BOT_GH_TOKEN }}

    steps:
    # 1️⃣ Checkout the repository
    - uses: actions/checkout@v4

    # 2️⃣ Extract user command
    - name: Extract Command
      id: command
      run: |
        echo "COMMAND=${{ github.event.comment.body }}" >> $GITHUB_ENV

    # 3️⃣ Process the request (generate or modify files)
    - name: Process Request
      run: |
        echo "Processing command: ${{ env.COMMAND }}"
        if [[ ${{ env.COMMAND }} == "/request Add Hello World comment" ]]; then
          # Example: Add Hello World comment
          echo "// Hello World" > temp_file
          cat A\ Fun\ Universe/Assets/Scripts/IcoSphere.cs >> temp_file
          mv temp_file A\ Fun\ Universe/Assets/Scripts/IcoSphere.cs
          git add A\ Fun\ Universe/Assets/Scripts/IcoSphere.cs
          git commit -m "Added Hello World comment"
        fi

    # 4️⃣ Push changes and create pull request
    - name: Push changes & create pull request
      run: |
        git push -u origin HEAD
        gh pr create \
          --title "Automated Update: ${{ env.COMMAND }}" \
          --body  "Change requested via issue comment: ${{ github.event.comment.html_url }}" \
          --head  automated-update \
          --base  main